In [5]:
import numpy as np

In [6]:
# Qn1:. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

# code->
arr = np.random.randint(1,100,(3,3))

In [7]:
arr

array([[ 4, 82, 47],
       [41, 72, 29],
       [42, 20,  7]])

In [6]:
arr.T

array([[58, 35, 66],
       [52, 73, 28],
       [90, 29, 23]])

In [7]:
# Qn2: Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

# code->
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [10]:
arr.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [30]:
# Qn3: Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array

# code->
arr = np.random.rand(4, 4)
bordered_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print("Original 4x4 Array:\n", arr)
print("6x6 Array with Border:\n", bordered_arr)

Original 4x4 Array:
 [[0.6628548  0.29513379 0.06383836 0.22955144]
 [0.44191847 0.32472618 0.95261442 0.71965673]
 [0.46626551 0.44728006 0.89469327 0.59440983]
 [0.18764535 0.42513193 0.07321387 0.70077344]]
6x6 Array with Border:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.6628548  0.29513379 0.06383836 0.22955144 0.        ]
 [0.         0.44191847 0.32472618 0.95261442 0.71965673 0.        ]
 [0.         0.46626551 0.44728006 0.89469327 0.59440983 0.        ]
 [0.         0.18764535 0.42513193 0.07321387 0.70077344 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [13]:
# Qn4: Using NumPy, create an array of integers from 10 to 60 with a step of 5.

# code->
arr = np.arange(10, 61, 5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

In [14]:
# Qn5: Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

# code->
str = np.array(['python', 'numpy', 'pandas'])
str

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [15]:
str.dtype

dtype('<U6')

In [16]:
str.ndim

1

In [17]:
# Applying various string manipulation functions from np.char module

In [18]:
np.char.upper(str)

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [19]:
np.char.lower(str)

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [22]:
np.char.capitalize(str) 

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [23]:
np.char.swapcase(str) #convert lowercase into uppercase and vice versa

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [24]:
np.char.title(str) # Capitalizing the first character of each word in the string

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [49]:
# Qn6: Generate a NumPy array of words. Insert a space between each character of every word in the array

# code->
arr = np.array(['hello', 'world'])
spaced_arr = np.char.join(' ', arr)
print("Original Array:\n", arr)
print("Array with spaces between characters:\n", spaced_arr)

Original Array:
 ['hello' 'world']
Array with spaces between characters:
 ['h e l l o' 'w o r l d']


In [34]:
# Qn7:. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division

# code->
arr1 = np.random.randint(1,10,(3,3))
arr1

array([[6, 5, 8],
       [7, 1, 4],
       [5, 5, 7]])

In [35]:
arr2 = np.random.randint(1,10,(3,3))
arr2

array([[2, 8, 7],
       [9, 4, 9],
       [4, 2, 1]])

In [36]:
# Addition
arr1+arr2

array([[ 8, 13, 15],
       [16,  5, 13],
       [ 9,  7,  8]])

In [37]:
arr1-arr2

array([[ 4, -3,  1],
       [-2, -3, -5],
       [ 1,  3,  6]])

In [38]:
arr1*arr2

array([[12, 40, 56],
       [63,  4, 36],
       [20, 10,  7]])

In [39]:
arr1/arr2

array([[3.        , 0.625     , 1.14285714],
       [0.77777778, 0.25      , 0.44444444],
       [1.25      , 2.5       , 7.        ]])

In [44]:
# Qn8:Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

# code->
identity_matrix = np.identity(5)
diagonal_elements = np.diag(identity_matrix)
print("5x5 Identity Matrix:\n", identity_matrix)
print()
print("Diagonal Elements:\n", diagonal_elements)

5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
 [1. 1. 1. 1. 1.]


In [46]:
# Qn9: Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

# code->
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

arr = np.random.randint(0, 1001, 100)
primes = arr[np.vectorize(is_prime)(arr)]
print("Random Array:\n", arr)
print()
print("Prime Numbers in Array:\n", primes)


Random Array:
 [798 214 634 873 846 535 447 428  97 757 207 171 911 942 865 966  65 222
 330 264 208 415 851 265 742 155 429 332 544 696 567 706 529 489 688 430
 244 560 988  29 900 494 866 613 670 497 844 144 501 590 976 903 525 264
 754 634 265 431 185 327 842 443 781  51 954 223 201 813 443 885 752 982
 821 436 718 454 484 215 507 446 202 160 676 849 847 448 811 537 731 873
 961   3 686  76 102 720 315 667 838 930]

Prime Numbers in Array:
 [ 97 757 911  29 613 431 443 223 443 821 811   3]


In [8]:
# Qn10: Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

# Ans:
daily_temperatures = np.random.randint(15, 36, 30)
daily_temperatures

array([23, 33, 16, 27, 34, 16, 30, 29, 35, 30, 15, 31, 30, 16, 32, 29, 31,
       31, 34, 35, 35, 34, 25, 23, 34, 34, 32, 16, 20, 34])

In [50]:
week1=daily_temperatures[0:7]
week2=daily_temperatures[7:14]
week3=daily_temperatures[14:21]
week4=daily_temperatures[21:28]

In [51]:
avg_week1=np.mean(week1)
avg_week2=np.mean(week2)
avg_week3=np.mean(week3)
avg_week4=np.mean(week4)

In [53]:
print("Average temperature of week1: ",avg_week1)
print("Average temperature of week2: ",avg_week2)
print("Average temperature of week3: ",avg_week3)
print("Average temperature of week4: ",avg_week4)

Average temperature of week1:  25.571428571428573
Average temperature of week2:  26.571428571428573
Average temperature of week3:  32.42857142857143
Average temperature of week4:  28.285714285714285
